workspace = { members = [] }
[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"
authors = ["Mathias APARICIO"]
default-run = "rust-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mock_tracker"
path = "src/mock_tracker.rs"

[[bin]]
name = "rust-client"
path = "src/main.rs"

[[bin]]
name = "com"
path = "src/com.rs"

[[bin]]
name = "userinput"
path = "src/userinput.rs"



[dependencies]
md5 = "0.7.0"
